### ISSUE TITLE
Support for Capacitor 6

### ISSUE THREAD

**Issue by AntonERG** [aparajita/capacitor-secure-storage-demo#2]
A question rather than issue - does the latest version support Capacitor 6?

Or, do you plan to make an update to support Capacitor 6?

**Comment by aparajita** [comment]
This is the demo, not the plugin. Please read the README for the plugin, Capacitor support is clearly stated. 🙏

**Comment by aparajita** [comment]
Link to the plugin is at the beginning of the README for this repo.
